# Generated by Django 2.1.7 on 2019-09-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_auto_20190629_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='img',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='url',
        ),
        migrations.AddField(
            model_name='advert',
            name='picture',
            field=models.ImageField(default='default/default.jfif', upload_to='advert_imgs'),
        ),
    ]
