# Generated by Django 2.1.7 on 2019-09-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_auto_20190922_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='url',
            field=models.CharField(default='def', max_length=500),
            preserve_default=False,
        ),
    ]
