# Generated by Django 2.1.7 on 2019-09-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_advert_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='url',
            field=models.CharField(default='test', max_length=500),
        ),
    ]
