# Generated by Django 2.1.7 on 2019-09-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0005_auto_20190922_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='img',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advert',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
