# Generated by Django 2.1.7 on 2019-06-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date',
        ),
    ]
