# Generated by Django 2.1.7 on 2019-06-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_trustee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trustee',
            old_name='position',
            new_name='conact_tel',
        ),
    ]
