# Generated by Django 2.1.7 on 2019-08-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20190630_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('img', models.CharField(default='https://image.flaticon.com/icons/svg/149/149071.svg', max_length=500)),
            ],
        ),
    ]
