# Generated by Django 2.1.7 on 2019-08-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_advisory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(default='https://image.flaticon.com/icons/svg/149/149071.svg', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Advisory',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='forename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='trustee',
            old_name='forename',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='trustee',
            name='surname',
        ),
    ]
