# Generated by Django 2.1.7 on 2019-08-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20190810_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='picture',
            field=models.ImageField(blank=True, upload_to='advisor'),
        ),
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, upload_to='management'),
        ),
        migrations.AddField(
            model_name='trustee',
            name='picture',
            field=models.ImageField(blank=True, upload_to='trustee'),
        ),
    ]
