# Generated by Django 2.1.7 on 2019-06-22 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190622_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(blank=True, max_length=10000, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
    ]
