# Generated by Django 2.1.7 on 2019-06-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190622_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='image',
        ),
    ]
