# Generated by Django 2.1.7 on 2019-07-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190630_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('contact', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=2000)),
            ],
        ),
    ]
