# Generated by Django 2.1.7 on 2019-08-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='project_imgs')),
                ('date', models.DateField()),
                ('text', models.CharField(max_length=10000)),
            ],
        ),
    ]
