# Generated by Django 2.1.7 on 2019-08-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='home',
            field=models.BooleanField(default=False),
        ),
    ]
