# Generated by Django 2.1.7 on 2019-08-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_article_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='home',
            field=models.BooleanField(default=False),
        ),
    ]
