# Generated by Django 2.1.7 on 2019-08-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_project_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Past',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, upload_to='event_imgs')),
                ('date', models.DateField()),
                ('text', models.CharField(max_length=10000)),
                ('home', models.BooleanField(default=False)),
            ],
        ),
    ]
