# Generated by Django 2.1.7 on 2019-08-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190815_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='guestt_imgs')),
                ('date', models.DateField()),
                ('text', models.CharField(max_length=10000)),
                ('home', models.BooleanField(default=False)),
                ('news', models.BooleanField(default=True)),
                ('event', models.BooleanField(default=True)),
                ('guest', models.BooleanField(default=False)),
                ('project', models.BooleanField(default=False)),
            ],
        ),
    ]
