# Generated by Django 2.1.7 on 2019-08-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='event',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='news',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='project',
            field=models.BooleanField(default=False),
        ),
    ]
