# Generated by Django 2.1.7 on 2019-08-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190831_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.AddField(
            model_name='event_past',
            name='news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='news',
            field=models.BooleanField(default=False),
        ),
    ]
