# Generated by Django 2.1.7 on 2019-08-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190831_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(default='static/pics/default.jfif', upload_to='project_imgs'),
        ),
    ]
