# Generated by Django 2.1.7 on 2019-08-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190831_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(default='pics/default.jfif', upload_to='project_imgs'),
        ),
    ]
