# Generated by Django 2.1.7 on 2019-08-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190831_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(default='default/default.jfif', upload_to='project_imgs'),
        ),
    ]
