# Generated by Django 2.1.7 on 2019-09-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20190831_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='default/default.jfif', upload_to='article_imgs'),
        ),
        migrations.AlterField(
            model_name='event_past',
            name='picture',
            field=models.ImageField(default='default/default.jfif', upload_to='event_imgs'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='picture',
            field=models.ImageField(default='default/default.jfif', upload_to='guestt_imgs'),
        ),
    ]
