# Generated by Django 2.1.7 on 2019-09-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20190901_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='event_past',
            name='aid',
            field=models.BooleanField(default=False),
        ),
    ]
